config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  get 'build', to: 'pages#build'
  get 'image', to: 'pages#image'
  get 'state', to: 'robot#state'
  get 'trajectory', to: 'pages#trajectory'

  get 'settings', to: 'settings#index'
  post 'update_config', to: 'settings#update'

  get 'calibrate', to: 'calibration#index'
  post 'adjust', to: 'calibration#adjust'
  post 'manual', to: 'calibration#manual'
  post 'move', to: 'calibration#move'

  post 'velocity', to: 'robot#velocity'
  post 'acceleration', to: 'robot#acceleration'
  post 'run', to: 'robot#run'
  post 'stop', to: 'robot#stop'
  post 'next', to: 'robot#next_trajectory'
  post 'prev', to: 'robot#prev_trajectory'
  post 'reset', to: 'robot#reset_trajectory'
end

app/views/pages/_joystick.html.haml
- redis = Redis.new
.row#start-from-block
  .col-sm-4
    = link_to 'Prev', 'javascript:void(0)', class: 'btn btn-warning btn-block', onclick: "update_trajectory('/prev')"
  .col-sm-4
    = link_to Config.start_from.to_i, 'javascript:void(0)', class: 'btn btn-block', id: 'start-from'
  .col-sm-4
    = link_to 'Next', 'javascript:void(0)', class: 'btn btn-warning btn-block', onclick: "update_trajectory('/next')"
.row
  .col-sm-12
    - running = redis.get('running')
    = link_to 'Run', 'javascript:void(0)', class: 'btn btn-danger btn-block', id: 'run', onclick: 'onRun()', style: "#{running ? 'display: none;' : ''}"
    = link_to 'Stop', 'javascript:void(0)', class: 'btn btn-danger btn-block', id: 'stop', onclick: 'onStop()', style: "#{running ? '' : 'display: none;'}"

app/views/pages/_status.html.haml
- velocity = Config.linear_velocity
- acceleration = Config.linear_acceleration
%dl.row
  %dt.col-sm-4
    Position
  %dd.col-sm-8
    x:
    %span#x
    y:
    %span#y
  %dt.col-sm-4
    Trajectory
  %dd.col-sm-8
    %span#current_trajectory
%hr
%dl.row
  %dt.col-sm-4
    Speed
  %dd.col-sm-8
    %span#speed
      = velocity.round
    mm/s
  %dt.col-sm-12
    =range_field_tag 'speed_range', velocity, class: 'custom-range', in: 0..500, step: 10, onchange: "onVelocityChange('#{layer_id}')"
  %hr
  %dt.col-sm-4
    Acceleration
  %dd.col-sm-8
    %span#acceleration
      = acceleration.round
    mm/s^2
  %dt.col-sm-12
    =range_field_tag 'acceleration_range', acceleration, class: 'custom-range', in: 0..500, step: 10, onchange: "onAccelerationChange('#{layer_id}')"

app/views/pages/main.html.haml
= javascript_include_tag 'pages'
= javascript_include_tag 'paint'

.alert.alert-danger#alert{style: 'display: none;'}
  %p
    Wrong canvas size.
  %p
    canvas_size_x =
    %span#canvas_size_x
      #{Config.canvas_size_x.to_i}
  %p
    initial_x =
    %span#initial_x
      #{Config.initial_x.to_i},
    initial_y =
    %span#initial_y
      #{Config.initial_y.to_i}
  %p
    svg size =
    %span#svg_size
      0


- layer_id = params[:layer]
.row
  .col-md-9
    %h5#image_name
      =@image.name
    -#%object{data: @layer, type: 'image/svg+xml', id: 'svg'}
    .svg#svg
      -#%svg(width="200" height="200" viewBox="0 0 200 200")
      = @layer.html_safe
  .col-md-3
    .row
      %h5#layer_name
        - layer_id ||= ''
        = layer_id
      .btn-group.btn-block.btn-group-vertical(role="group" aria-label="Layers")
        .btn-group(role="group")
          %button.btn.btn-secondary.btn-sm.dropdown-toggle#images(type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false")
            = 'Image: ' + @image.name
          .dropdown-menu(aria-labelledby="images")
            - @images.each do |image_name|
              - current = (image_name == @image.name) ? ' font-weight-bold' : ''
              = link_to image_name, image_path(image: image_name), class: 'dropdown-item btn btn-sm' + current


        .btn-group(role="group")
          %button.btn.btn-secondary.btn-sm.dropdown-toggle#ibtnGroupDrop(type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false")
            = 'Layer: ' + layer_id
          .dropdown-menu(aria-labelledby="btnGroupDrop")
            = link_to 'Whole image', root_path, class: 'dropdown-item btn btn-sm'
            %hr
            - @image.layers.keys.each do |layer_name|
              - current = (layer_id == layer_name) ? ' font-weight-bold' : ''
              = link_to layer_name, root_path(layer: layer_name), class: 'dropdown-item btn btn-sm' + current, onclick: "update_trajectory('/reset')"

        %hr
        - unless layer_id.nil?
          = link_to 'Build', build_path(layer: layer_id), class: 'btn btn-info', style: "#{layer_id.empty? ? 'display: none;' : ''}"
          = link_to 'Simulate', 'javascript:void(0)', class: 'btn btn-info', onclick: "paint(#{@velocity})"
        %hr
        = link_to 'Settings', settings_path, class: 'btn btn-light', target: '_blank'
        = link_to 'Calibration', calibrate_path, class: 'btn btn-secondary', target: '_blank'
    .row
    = render partial: 'status', locals: {layer_id: layer_id}
    .row
    = render partial: 'joystick'