config/routes.rb
Rails.application.routes.draw do
  root 'pages#main'
  get 'build', to: 'pages#build'
  get 'image', to: 'pages#image'
  get 'state', to: 'robot#state'
  get 'trajectory', to: 'pages#trajectory'

  get 'settings', to: 'settings#index'
  post 'update_config', to: 'settings#update'

  get 'calibrate', to: 'calibration#index'
  post 'adjust', to: 'calibration#adjust'
  post 'manual', to: 'calibration#manual'
  post 'move', to: 'calibration#move'

  post 'velocity', to: 'robot#velocity'
  post 'acceleration', to: 'robot#acceleration'
  post 'run', to: 'robot#run'
  post 'stop', to: 'robot#stop'
  post 'next', to: 'robot#next_trajectory'
  post 'prev', to: 'robot#prev_trajectory'
  post 'reset', to: 'robot#reset_trajectory'
end

app/controllers/calibration_controller.rb
class CalibrationController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [:manual]
  before_action :set_redis

  def index
    state = helpers.get_state
    @left_mm = state[:left_mm]
    @right_mm = state[:right_mm]
  end

  def manual
    @redis.publish('commands', {command: 'manual', motor: params[:motor], direction: params[:direction], distance: params[:distance]}.to_json)
    head :ok
  end

  def move
    @redis.publish('commands', {command: 'move', x: params[:x], y: params[:y]}.to_json)
    redirect_to calibrate_path
  end

  def adjust
    motor = params[:left].present? ? 'left' : 'right'
    mm = params[motor].to_f
    actual_position = Point.new(mm, mm).get_motors_deg.x
    @redis.publish('commands', {command: 'correct', motor: motor, actual_position: actual_position}.to_json)
    redirect_to calibrate_path
  end

  def set_redis
    @redis = Redis.new
  end
end

app/views/calibration/_motor.html.haml
%h5
  = motor
.row
  .col-6
    %h5 Manual control, mm
    .form-group
      .row
        .col-12
          =link_to 'up', 'javascript:;', class: "btn btn-secondary", id: "up-#{motor}"
      .row
        .col-12
          =text_field_tag "value_#{motor}", '10.0', class: 'form-control', id: "value-#{motor}"
      .row
        .col-12
          =link_to 'down', 'javascript:;', class: "btn btn-secondary", id: "down-#{motor}"

%hr
.row
  .col-12
    %h5 This position corresponds to, mm
    = form_tag adjust_path, class: 'form-inline' do
      .form-group.mb-2
        =text_field_tag motor, belt_length, class: 'form-control'
      =submit_tag 'adjust', class: 'btn btn-secondary mb-2', method: :post

app/views/calibration/index.html.haml
= javascript_include_tag 'calibrate'
State:
.row
%dl.row
  %dt.col-sm-1 Left_mm:
  %dd.col-sm-11#left-mm
  %dt.col-sm-1 Right_mm
  %dd.col-sm-11#right-mm
  %dt.col-sm-1 Left_deg
  %dd.col-sm-11#left-deg
  %dt.col-sm-1 Right_deg
  %dd.col-sm-11#right-deg
  %dt.col-sm-1 x
  %dd.col-sm-11#x
  %dt.col-sm-1 y
  %dd.col-sm-11#y
  %dt.col-sm-1 Running:
  %dd.col-sm-11#running
%hr
.row
  .col-6
    = render partial:'motor', locals: {motor: :left, belt_length: @left_mm}
  .col-6
    = render partial:'motor', locals: {motor: :right, belt_length: @right_mm}

%hr
.row
  .col-3
    %h5 Move to, mm, decart
    = form_tag move_path, class: 'mb-2' do
      .form-group
        =label_tag "X"
        =text_field_tag "x", '110.0', class: 'form-control'
      .form-group
        =label_tag "Y"
        =text_field_tag "y", '110.0', class: 'form-control'
      =submit_tag 'move to', class: 'btn btn-secondary mb-2'
%hr